apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "users.fullname" . }}
  labels:
    app: {{ template "users.name" . }}
    chart: {{ template "users.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "users.name" . }}
      release: {{ .Release.Name }}
  strategy:
    blueGreen:
      activeService: {{ template "users.fullname" . }}
      previewService: {{ template "users.fullname" . }}-preview
  template:
    metadata:
      labels:
        app: {{ template "users.name" . }}
        release: {{ .Release.Name }}
        version: {{ .Values.image.tag }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: profile
            - name: spring.cloud.consul.host
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: consul_host
            - name: spring.cloud.consul.port
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: consul_port
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}