apiVersion: v1
kind: Service
metadata:
  name: {{ include "users.fullname" . }}
  labels:
    app: {{ template "users.name" . }}
    chart: {{ template "users.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.image.tag }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "users.name" . }}
    release: {{ .Release.Name }}
    version: {{ .Values.image.tag }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "users.fullname" . }}-preview
  labels:
    app: {{ template "users.name" . }}
    chart: {{ template "users.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.image.tag }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "users.name" . }}
    release: {{ .Release.Name }}
    version: {{ .Values.image.tag }}