apiVersion: v1
kind: Namespace
metadata:
  name: springcloud
  labels:
    name: springcloud
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clustercamp
  namespace: springcloud
data:
  active.profiles: dev
  config.host: http://config.springcloud.svc.cluster.local:8888
  zipkin.host: http://zipkin.springcloud.svc.cluster.local:9411
  eureka.host: http://eureka.springcloud.svc.cluster.local:8761/eureka
  eureka.datacenter: Cluster Camp
  eureka.environment: Kubernetes on Arm64v8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-springcloud-namespace
subjects:
  - kind: ServiceAccount
    name: default
    namespace: springcloud
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
