apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
spec:
  replicas: quick-start.sh
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: pvc-jenkins
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        resources:
          requests:
            cpu: 500m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 6000Mi
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlp-port
          containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  namespace: devops
spec:
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ci
  namespace: devops
spec:
  rules:
  - host: ci.k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
