apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ccs
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Hyundai Motor Company Connected Car Service
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy

  #  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  #  namespaceResourceWhitelist:
  #    - group: 'apps'
  #      kind: Deployment
  #    - group: 'apps'
  #      kind: StatefulSet

  orphanedResources:
    warn: false

  roles:
    - name: ci-role
      description: Sync privileges
      policies:
        - p, proj:my-project:admin, repositories, update, my-project/https://code.hcloud.hmc.co.kr/ccs/*, allow


